#!/usr/bin/env python3
"""
fetch-route.py — stage 1: ask a routing engine for the real road geometry.

Reads tools/route.config.json, requests a route through its waypoints, and
writes the raw full-resolution geometry to the configured raw_output.

    python3 tools/fetch-route.py              # fetch, then simplify + write
    python3 tools/fetch-route.py --fetch-only # just refresh the raw geometry
    python3 tools/fetch-route.py --dry-run    # print the URL, touch nothing

Stage 2 is tools/route-from-track.py, which simplifies the raw geometry and
writes route-data.js plus the GPX/KML. It is invoked automatically unless
--fetch-only is given. Re-tuning tolerance_m therefore costs no HTTP request:
just run stage 2 directly on the cached raw file.

The raw geometry is deliberately kept on disk. It is the evidence for what the
map claims, and it lets the corridor be re-simplified without hammering a free
public API.
"""

import json
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "tools" / "route.config.json"
TIMEOUT_S = 120


def load_config():
    cfg = json.loads(CONFIG.read_text(encoding="utf-8"))
    pts = [w for w in cfg["waypoints"] if not w.get("disabled")]
    if len(pts) < 2:
        raise SystemExit("Need at least two enabled waypoints.")
    cfg["waypoints"] = pts
    return cfg


def build_url(cfg):
    r = cfg["router"]
    coords = ";".join(f"{w['lng']:.7f},{w['lat']:.7f}" for w in cfg["waypoints"])
    params = ["overview=full", "geometries=geojson", "steps=false", "annotations=false"]
    if r.get("continue_straight") is False:
        params.append("continue_straight=false")
    radii = [w.get("radius_m") for w in cfg["waypoints"]]
    if any(x is not None for x in radii):
        params.append("radiuses=" + ";".join("" if x is None else str(int(x)) for x in radii))
    return (f"{r['base_url'].rstrip('/')}/route/v1/{r['profile']}/{coords}"
            f"?{'&'.join(params)}")


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "roadbook-pwa/route-fetch"})
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT_S) as resp:
            doc = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        raise SystemExit(f"Router returned HTTP {e.code}: {e.read()[:400].decode('utf-8', 'replace')}")
    except urllib.error.URLError as e:
        raise SystemExit(f"Could not reach the router: {e.reason}")
    if doc.get("code") != "Ok":
        raise SystemExit(f"Router said {doc.get('code')}: {doc.get('message', '')}")
    if not doc.get("routes"):
        raise SystemExit("Router returned no route.")
    return doc


def report(doc, cfg):
    """Per-leg distances and snap distances.

    Both are correctness signals, not decoration. A waypoint that snapped a
    long way from where it was placed is on the wrong road; a leg distance
    that disagrees with the roadbook notes means the router chose a path the
    trip was not planned around - which matters most for the fuel gaps.
    """
    route = doc["routes"][0]
    names = [w["name"] for w in cfg["waypoints"]]

    print(f"\ntotal       {route['distance'] / 1000:,.0f} km, "
          f"{route['duration'] / 3600:.1f} h moving\n")

    print("leg distances")
    for i, leg in enumerate(route.get("legs", [])):
        print(f"  {names[i][:26]:<26} -> {names[i+1][:26]:<26} {leg['distance']/1000:7,.1f} km")

    far = [(names[i], w.get("distance", 0.0))
           for i, w in enumerate(doc.get("waypoints", []))
           if w.get("distance", 0.0) > 500]
    if far:
        print("\n!! snapped far from the placed coordinate - check these on the map:")
        for name, d in far:
            print(f"  {name:<30} {d:,.0f} m")


def write_raw(doc, cfg):
    route = doc["routes"][0]
    out = ROOT / cfg.get("raw_output", "tools/route.raw.geojson")
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "type": "Feature",
        "properties": {
            "source": f"{cfg['router']['base_url']} profile={cfg['router']['profile']}",
            "distance_km": round(route["distance"] / 1000, 1),
            "duration_h": round(route["duration"] / 3600, 2),
            "waypoints": [w["name"] for w in cfg["waypoints"]],
            "note": "Full-resolution router output. Generated by tools/fetch-route.py "
                    "- do not hand-edit; edit tools/route.config.json and re-run.",
        },
        "geometry": route["geometry"],
    }
    out.write_text(json.dumps(payload, indent=1), encoding="utf-8")
    print(f"\nwrote       {out.relative_to(ROOT)}  "
          f"({len(route['geometry']['coordinates']):,} points)")
    return out


def main():
    args = sys.argv[1:]
    cfg = load_config()
    url = build_url(cfg)

    if "--dry-run" in args:
        print(url)
        return

    print(f"routing {len(cfg['waypoints'])} waypoints via {cfg['router']['base_url']} "
          f"({cfg['router']['profile']})")
    doc = fetch(url)
    report(doc, cfg)
    raw = write_raw(doc, cfg)

    if "--fetch-only" in args:
        print("\n--fetch-only: stopping before stage 2.")
        return
    print()
    subprocess.run([sys.executable, str(ROOT / "tools" / "route-from-track.py"),
                    str(raw), str(cfg.get("tolerance_m", 12))], check=True)


if __name__ == "__main__":
    main()
